[Options]
subdomain="http://check.getipintel.net/check.php"
email="InsertYourEmailHere"
cacheClearInterval=86400
#DO NOT CHANGE THE VERSION
configVersion=1.1
[Messages]
usingVPN="Topaz RESPONSE!"
errorKick="Topaz ERROR!"